services:
  server-nginx:
    image: nginx:alpine
    container_name: server-nginx
    ports:
      - "80:80"
    volumes:
      - "./server-entrypoint/nginx-mobile.conf:/etc/nginx/nginx.conf:ro"
      - "./server-entrypoint/proxy_params:/etc/nginx/proxy_params:ro"
    depends_on:
      - backend-api-forum
      - backend-api-instructor
      - backend-api-public1
      - backend-api-student
      - backend-api-user
    networks:
      - iamra_net

  database-mysql:
    image: mysql:latest
    container_name: database-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: iamra_course
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - iamra_net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      retries: 10
      timeout: 10s
    mem_limit: 512m
    cpus: 0.8

  database-redis:
    image: redis:latest
    container_name: database-redis
    ports:
      - "6379:6379"
    networks:
      - iamra_net
    mem_limit: 100m
    cpus: 0.05

  database-mongo:
    image: mongo:latest
    container_name: database-mongo
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - iamra_net
    mem_limit: 512m
    cpus: 0.2

  backend-api-user:
    build:
      context: ../../
      dockerfile: docker/dev/backend-laravel/user/Dockerfile.api-user
    container_name: backend-api-user
    volumes:
      - "../../backend-api-user:/app"
    depends_on:
      database-mysql:
        condition: service_healthy
      database-redis:
        condition: service_started
      database-mongo:
        condition: service_started
    env_file:
      - "backend-laravel/_shared/.env.shared"
      - "../../backend-api-user/.env"
    networks:
      - iamra_net
    mem_limit: 200m
    cpus: 0.1

  backend-api-user-reverb:
    build:
      context: ../../
      dockerfile: docker/dev/backend-laravel/user/Dockerfile.api-user-reverb
    container_name: backend-api-user-reverb
    volumes:
      - "../../backend-api-user:/app"
    depends_on:
      database-redis:
        condition: service_started
    env_file:
      - "backend-laravel/_shared/.env.shared"
      - "../../backend-api-user/.env"
    networks:
      - iamra_net
    mem_limit: 200m
    cpus: 0.1

  backend-api-user-queue:
    build:
      context: ../../
      dockerfile: docker/dev/backend-laravel/user/Dockerfile.api-user-queue
    container_name: backend-api-user-queue
    volumes:
      - "../../backend-api-user:/app"
    ports:
      - "9595:80"
    depends_on:
      - backend-api-user
      - database-redis
    env_file:
      - "backend-laravel/_shared/.env.shared"
      - "../../backend-api-user/.env"
    networks:
      - iamra_net
    mem_limit: 200m
    cpus: 0.1
    healthcheck:
      test: [ "NONE" ]

  backend-api-student:
    build:
      context: ../../
      dockerfile: docker/dev/backend-laravel/student/Dockerfile.api-student
    container_name: backend-api-student
    volumes:
      - "../../backend-api-student:/app"
    depends_on:
      database-mysql:
        condition: service_healthy
      database-redis:
        condition: service_started
      database-mongo:
        condition: service_started
    env_file:
      - "backend-laravel/_shared/.env.shared"
      - "../../backend-api-student/.env"
    networks:
      - iamra_net
    mem_limit: 200m
    cpus: 0.1

  backend-api-instructor:
    build:
      context: ../../
      dockerfile: docker/dev/backend-laravel/instructor/Dockerfile.api-instructor
    container_name: backend-api-instructor
    volumes:
      - "../../backend-api-instructor:/app"
    depends_on:
      database-mysql:
        condition: service_healthy
      database-redis:
        condition: service_started
      database-mongo:
        condition: service_started
    env_file:
      - "backend-laravel/_shared/.env.shared"
      - "../../backend-api-instructor/.env"
    networks:
      - iamra_net
    mem_limit: 200m
    cpus: 0.1

  backend-api-forum:
    build:
      context: ../../
      dockerfile: docker/dev/backend-laravel/forum/Dockerfile.api-forum
    container_name: backend-api-forum
    volumes:
      - "../../backend-api-forum:/app"
    depends_on:
      - backend-api-user
      - database-mongo
    env_file:
      - "backend-laravel/_shared/.env.shared"
      - "../../backend-api-forum/.env"
    networks:
      - iamra_net
    mem_limit: 200m
    cpus: 0.1

  backend-api-forum-reverb:
    build:
      context: ../../
      dockerfile: docker/dev/backend-laravel/forum/Dockerfile.api-forum-reverb
    container_name: backend-api-forum-reverb
    volumes:
      - "../../backend-api-forum:/app"
    depends_on:
      - database-redis
      - database-mongo
    env_file:
      - "backend-laravel/_shared/.env.shared"
      - "../../backend-api-forum/.env"
    networks:
      - iamra_net
    mem_limit: 200m
    cpus: 0.1

  backend-api-public1:
    build:
      context: ../../
      dockerfile: docker/dev/backend-laravel/public/Dockerfile.api-public
    container_name: backend-api-public1
    volumes:
      - "../../backend-api-public:/app"
    depends_on:
      database-mysql:
        condition: service_healthy
      database-redis:
        condition: service_started
      database-mongo:
        condition: service_started
    env_file:
      - "backend-laravel/_shared/.env.shared"
      - "../../backend-api-public/.env"
    networks:
      - iamra_net
    mem_limit: 200m
    cpus: 0.1

volumes:
  mysql_data:
    name: mysql_data
  mongo_data:
    name: mongo_data

networks:
  iamra_net:
    driver: bridge