<?php

namespace Tests\Feature\Auth;

use Illuminate\Foundation\Testing\TestCase;
use Tests\utils\Helper;

class LoginWithGoogleTest extends TestCase
{
    private static string $url;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        self::$url = config('api.version') . '/auth';
    }

    function test_user_berhasil_login_with_google()
    {
        $res = $this->postJson(self::$url . '/login-with-google', [
            'email' => Helper::USERNAME . '@gmail.com',
        ]);

        $res->assertStatus(200)
            ->assertJson([
                "success" => true,
                "message" => "Login successfully"
            ]);
        Helper::deleteUser(strrev(Helper::USERNAME));
    }

    function test_user_gagal_login_with_google_karena_tidak_mengirimkan_data_apapun()
    {
        $res = $this->postJson(self::$url . '/login-with-google', [
            'email' => '',
        ]);

        $res->assertStatus(422)
            ->assertJson([
                    "success" => false,
                    "message" => "The email field is required."
            ]);
    }
}
