<?php

namespace Tests\Feature\Auth;

use Illuminate\Foundation\Testing\TestCase;
use Tests\utils\Helper;

class LoginTest extends TestCase
{
    private static string $url;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        self::$url = config('api.version') . '/auth';
    }

    function test_user_berhasil_login()
    {
        Helper::insertUser();
        $res = $this->postJson(self::$url . '/login', [
            'username' => Helper::USERNAME,
            'password' => Helper::PASSWORD
        ]);

        $res->assertStatus(200)
            ->assertJson([
                "success" => true,
                "message" => "Login successfully"
            ]);

        Helper::deleteUser();
    }

    function test_user_gagal_login_karena_tidak_mengirimkan_data_apapun()
    {
        $res = $this->postJson(self::$url . '/login', [
            'username' => '',
            'password' => ''
        ]);

        $res->assertStatus(422)
            ->assertJson([
                    "success" => false,
                    "message" => "Validation failed"
            ])
            ->assertJsonFragment([
                'username' => ['The username field is required.'],
                'password' => ['The password field is required.'],
            ]);
    }

    function test_user_gagal_login_karena_user_tidak_ada_atau_kata_sandi_salah()
    {
        $res = $this->postJson(self::$url . '/login', [
            'username' => 'johndoe',
            'password' => 'John123!'
        ]);

        $res->assertStatus(401)
            ->assertJson([
                "success" => false,
                "message" => "Username or password invalid"
            ]);
    }
}
