version: "3"

rpc:
  listen: tcp://127.0.0.1:6001

server:
  command: "php artisan octane:start --server=roadrunner --port=8000"
  relay: pipes

http:
  # Pakai Unix socket instead of TCP
  address: unix:///var/run/rr-user.sock

  pool:
    num_workers: 1
    max_jobs: 0
    allocate_timeout: 60s
    destroy_timeout: 60s

logs:
  mode: production
  level: error
  encoding: json
  output: stdout
