version: "3"

rpc:
  listen: tcp://127.0.0.1:6001

server:
  command: "php artisan octane:start --server=roadrunner --host=0.0.0.0 --port=8000"
  relay: pipes

http:
  address: unix:///var/run/sockets/backend-api-forum.sock
  pool:
    num_workers: 4

logs:
  mode: production
  level: error
  encoding: json
  output: stdout