version: "3"

# RPC untuk management & monitoring
rpc:
  listen: tcp://127.0.0.1:6001

# Server configuration
server:
  command: "php /app/worker.php"
  relay: pipes


# HTTP Server - UNIX SOCKET MODE
http:
  address: unix:///var/run/sockets/backend-api-forum.sock
  middleware: [ "headers", "gzip"]
  # Worker pool configuration
  pool:
    num_workers: 1
    max_jobs: 200
    allocate_timeout: 60s
    destroy_timeout: 60s

    supervisor:
      watch_tick: 1s
      ttl: 0s
      idle_ttl: 10s
      exec_ttl: 60s
      max_worker_memory: 90

  # Headers middleware
  headers:
    # Response headers
    response:
      X-Powered-By: "ilhamrhmtkbr"
      X-Frame-Options: "SAMEORIGIN"

# Logging configuration
logs:
  mode: production
  level: info
  encoding: console
  output: stdout
  err_output: stderr

# Hot reload untuk development (DISABLE di production!)
#reload:
#  interval: 1s
#  patterns: [".php"]
#  services:
#    http:
#      dirs: ["app", "config", "routes", "bootstrap", "resources/views"]
#      recursive: true
#      ignore: ["vendor", "storage", "node_modules", "public", "tests"]


# Resource limits
limits:
  services:
    http:
      max_memory: 112
      ttl: 0s
      idle_ttl: 10s
      exec_ttl: 60s
