version: "3"

rpc:
  listen: tcp://127.0.0.1:6001

http:
  address: unix:///var/run/sockets/backend-api-user.sock
  pool:
    num_workers: 4

logs:
  mode: production
  level: error
  encoding: json
  output: stdout