version: "3"

rpc:
  listen: tcp://127.0.0.1:6001

server:
  command: "php artisan octane:start --server=roadrunner"
  relay: "unix:///var/run/sockets/backend-api-instructor.sock"

http:
  address: "unix:///var/run/sockets/backend-api-instructor.sock"
  middleware: ["gzip", "headers"]
  pool:
    num_workers: 1
    max_jobs: 50
    allocate_timeout: 180s
    destroy_timeout: 60s
    supervisor:
      watch_tick: 1s
      ttl: 0
      idle_ttl: 10s
      exec_ttl: 120s
      max_worker_memory: 82
  headers:
    response:
      X-Powered-By: "RoadRunner"
  static:
    dir: "public"
    forbid: [".php", ".htaccess"]

logs:
  mode: production
  level: error
  encoding: json
  output: stdout
  channels:
    http:
      level: error
    server:
      level: error
