version: "3"

rpc:
  listen: tcp://127.0.0.1:6001

http:
  address: unix:///var/run/sockets/backend-api-instructor.sock
  pool:
    num_workers: 1 
    max_jobs: 50 
    allocate_timeout: 60s
    destroy_timeout: 60s

logs:
  mode: production
  level: error
  encoding: json
  output: stdout