<?php

namespace Tests;

use Illuminate\Foundation\Testing\TestCase as BaseTestCase;
use Illuminate\Support\Facades\Http;
use Tests\utils\Repository;

abstract class TestCase extends BaseTestCase
{
    public string $userToken;
    public string $instructorToken;
    public string $studentToken;
    public string $url;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        Repository::insertUser();
        Repository::insertInstructor();
        Repository::insertStudent();
        $this->url = config('api.version');
        $this->userToken = $this->getToken(Repository::USER_USERNAME, Repository::USER_PASSWORD);
        $this->instructorToken = $this->getToken(Repository::INSTRUCTOR_USERNAME, Repository::INSTRUCTOR_PASSWORD);
        $this->studentToken = $this->getToken(Repository::STUDENT_USERNAME, Repository::STUDENT_PASSWORD);
    }

    public function getToken(string $username, string $password): ?string
    {
        $res = Http::post('http://backend-api-user:8080/' . env('USER_API_VERSION') . '/auth/login', [
            'username' => $username,
            'password' => $password
        ]);
        $cookies = $res->header('Set-Cookie');
        preg_match('/access_token=([^;]+)/', $cookies, $matches);

        return $matches[1] ?? null;
    }

    protected function tearDown(): void
    {
        Repository::deleteUser();
        Repository::deleteInstructor();
        Repository::deleteStudent();
        parent::tearDown(); // TODO: Change the autogenerated stub
    }
}
