global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'k6-load-testing'

scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: [ 'set-node-exporter:9100' ]