import {api} from "./api.js";

export const accountFetch = () => api.get('/account');
export const accountStore = data => api.post('/account', data);
export const accountModify = data => api.patch('/account', data);
export const answersFetch = (page, sort) => api.get(`/answers?page=${page}&sort=${sort}`);
export const answerStore = data => api.post('/answers', data);
export const answerModify = data => api.patch('/answers', data);
export const coursesFetch = (page, sort) => api.get(`/courses?page=${page}&sort=${sort}`);
export const courseFetch = id => api.get(`/courses/show?id=${id}`);
export const courseStore = data => api.post('/courses', data);
export const courseModify = data => api.patch('/courses', data);
export const courseDelete = courseId => api.delete(`/courses?id=${courseId}`);
export const courseLikesFetch = (page, sort) => api.get(`/courses/likes?page=${page}&sort=${sort}`);
export const courseReviewsFetch = (page, sort) => api.get(`/courses/reviews?page=${page}&sort=${sort}`);
export const coursesCouponFetch = (page, sort) => api.get(`/coupons?page=${page}&sort=${sort}`);
export const courseCouponFetch = id => api.get(`/coupons/show?id=${id}`);
export const courseCouponStore = data => api.post('/coupons', data);
export const courseCouponModify = data => api.patch('/coupons', data);
export const courseCouponDelete = id => api.delete(`/coupons?id=${id}`);
export const earningsFetch = (page, sort) => api.get(`/earnings?page=${page}&sort=${sort}`);
export const earningPayout = () => api.post('/earnings');
export const lessonsFetch = (page, sectionId) => api.get(`/lessons?page=${page}&section_id=${sectionId}`);
export const lessonStore = data => api.post('/lessons', data);
export const lessonModify = data => api.patch('/lessons', data);
export const lessonDelete = (sectionId, lessonId) => api.delete(`/lessons?instructor_section_id=${sectionId}&id=${lessonId}`);
export const sectionsFetch = (page, courseId) => api.get(`/sections?course_id=${courseId}&page=${page}`);
export const sectionStore = data => api.post('/sections', data);
export const sectionModify = data => api.patch('/sections', data);
export const sectionDelete = sectionId => api.delete(`/sections?id=${sectionId}`);
export const socialsFetch = () => api.get('/socials');
export const socialStore = data => api.post('/socials', data);
export const socialModify = data => api.patch('/socials', data);
export const socialDelete = socialId => api.delete(`/socials?id=${socialId}`);